### ISSUE TITLE
Add Discord PTB

### ISSUE THREAD

**Issue by MacgyverJohnson** [crazy-max/discord-portable#2]
@crazy-max 
I have been wondering around for eons for this so thanks in petrodollars 👍
Hoping to requesting for a feature:
Can you portablize PTB(private test build) as well....? Can I just copy contents of app folder [C:\Users\MacGyver\AppData\Local\DiscordPTB\app-0.0.32\DiscordPTB.exe] to $InstallDIR\app-0.0.3.x ?
Thanks in Advance

**Comment by crazy-max** [comment]
@MacgyverJohnson

Your welcome ;)
For your request, in fact PTB is _Public Test Build_ and yes i can portablize this one too but in an other repository. I think it works the same way as this one.
I keep you in touch.

**Comment by crazy-max** [comment]
PTB (Public Test Build) portable version of Discord is available here : https://github.com/crazy-max/discord-ptb-portable
