### ISSUE TITLE
antivirus blocking discord-portable.exe

### ISSUE THREAD

**Issue by wokawoka** [crazy-max/discord-portable#3]
Hello,
I just did try to run the latest version (0.0.298-10) of discord portable but my installation of avast antivirus did block and removed it labelling the exe as Win32:Malware-gen .
I did a quick test on virustotal and actually there are 12 more antivirus programs other than avast considering it as virus.
https://www.virustotal.com/#/file/e9e58946ff392e863efe72aeb107671fe253c4dece599f3ccb9d381417d8f1c0/analysis/1502548486/
Even if I believe that this may just be a false positive (due to exe compression or packing?), I imagine that this may affect many other users and even scare them and prevent them to use the program.
Thank you and keep up the good work!

**Comment by crazy-max** [comment]
Hi @wokawoka,

Win32:Malware-gen and others found by the VirusTotal scan are generic.
Most likely based on a heuristic detection. Heuristics are more prone to false-positive detections.
You can have more info about here : https://malwaretips.com/blogs/win32evo-gen-susp-virus/

I keep this issue opened for now and i will investigate on this.
And thanks for your contrib!

**Comment by mrnategeek** [comment]
You know what? Move to a another framework "PortableApps", url is http://portableapps.com. I use that over 4 years and my antivirus has not detected a virus from them

**Comment by crazy-max** [comment]
Must be solved in the latest release (0.0.298-12)

**Comment by couponstechie** [comment]
I got a virus today that nothing will remove. I've tried RKill, Zemana, HitmanPro, ESET,
Now I have switched my anti-virus to Norton. 
http://couponstechie.blogspot.in/2017/11/do-you-need-norton-wifi-privacy.html
