### ISSUE TITLE
discord_voice.node error

### ISSUE THREAD

**Issue by kikoreta** [crazy-max/discord-portable#4]
discord open with a black window and in the console show this error: Uncaught Error: The specified module can not be found.
\\?\E:\Programas\Portables\Discord\data\0.0.298\modules\discord_voice\discord_voice.node

**Comment by MarioMasta64** [comment]
an easy way to fix this (directed at the developer) is to extract the discord to a directory and have another directory set "UserProfile" all data will be kept locally. (some ie cache stuff and a few things will also store here along with msft stuff) on another note id like to see how you fix this. i like your project keep it up.

**Comment by crazy-max** [comment]
Solved in the latest release (0.0.298-12)

**Comment by MarioMasta64** [comment]
im curious. howddya do it? (or was it a discord issue?)

**Comment by crazy-max** [comment]
Yep a Discord issue for me

**Comment by MarioMasta64** [comment]
thats one risk of portable-izing, an application has issues and now you have them xD also: virus scanners are great amirite? anything that comes into existence is basically a virus XD the best part is not knowing if you messed up or an application did. :D

**Comment by crazy-max** [comment]
Yes it's not false! The executable created to make the portable application is a simple wrapper around the executable of Discord so in my opinion I greatly minimize the risks of bugs.
On the other hand, the antivirus detection and the signature of the executable is a recurring problem with the Go language :(

**Comment by MarioMasta64** [comment]
"go" language? i use batch for all my stuff as you probably see (and rather chaotic yet controlled coding methods) ;P

**Comment by crazy-max** [comment]
Batch is a scripting language and is not so endorsed by end users ^^

**Comment by MarioMasta64** [comment]
people seem okay with it as far as i know and i <3 batch whats go language btw?

**Comment by crazy-max** [comment]
What is golang ? : https://www.computerhope.com/jargon/g/golang.htm
Official website : https://golang.org/
Golang code of discord-portable : https://github.com/crazy-max/discord-portable/blob/master/main.go

Hope this helps ;)

**Comment by MarioMasta64** [comment]
fancy. i have a friend who makes alot of stuff in auto-it, another in python, me in batch, and now (maybe you? (friend thing)) in go :D
