### ISSUE TITLE
Compatibility with BetterDiscord?

### ISSUE THREAD

**Issue by DaMatrix** [crazy-max/discord-portable#5]
Hi! I'm trying to install BetterDiscord along side this for amazing portability + kewl themes. The installer crashes before finishing. Any chance you could make it compatible?

Thanks!

**Comment by MarioMasta64** [comment]
heres a hint. its a basic.net archive ;P it's not too hard to do it

**Comment by crazy-max** [comment]
You can use DiscordPTB Portable for this purpose : https://github.com/crazy-max/discord-ptb-portable

![image](https://user-images.githubusercontent.com/1951866/30473821-f0620064-9a01-11e7-810b-c22903502410.png)

![image](https://user-images.githubusercontent.com/1951866/30473832-f5aabb2e-9a01-11e7-8b86-fb14fb5319fa.png)

**Comment by DaMatrix** [comment]
ok, thanks!
